- hosts: all
  vars_files:
  - vars.yml
  #- vars_generated.yml
  - passwd.yml

  collections:
    - redhat.satellite

  pre_tasks:
    - name: Copy manifest to target Satellite
      copy:
        src: "~/manifest.zip"
        dest: /root/manifest.zip
    - name: Retrieve GPG keys for later use
      set_fact:
        satellite_content_credentials: "{{ satellite_content_credentials | default([]) | union([{ 'name': item.name, 'content_type': 'gpg_key', 'content': lookup('url', item.url) }]) }}"
      loop: "{{ gpg_keys }}"

  roles: 
    - role: redhat.satellite.manifest
      vars:
        satellite_server_url: "{{ sat_url }}"
        satellite_username: "{{ sat_user }}"
        satellite_password: "{{ sat_passwd }}"
        satellite_organization: "{{ organization }}"
        satellite_manifest_path: "/root/manifest.zip"
      tags: manifest
    - role: firewalld
      tags: firewalld
    - role: locations
    - role: proxy
    - role: redhat.satellite.settings
      vars:
        satellite_server_url: "{{ sat_url }}"
        satellite_username: "{{ sat_user }}"
        satellite_password: "{{ sat_passwd }}"
        satellite_settings:
          http_proxy: "{{ default_http_proxy_url|default(omit) }}"
          content_default_http_proxy: "{{ default_http_proxy_url is defined | ternary('default_http_proxy', omit) }}"
          default_redhat_download_policy: "{{ rh_repo_download_policy|default(omit) }}"
          default_download_policy: "{{ custom_repo_download_policy|default(omit) }}"
          default_proxy_download_policy: "{{ capsule_repo_download_policy|default(omit) }}"
      tags: settings
    - role: redhat.satellite.content_credentials
      vars:
        satellite_server_url: "{{ sat_url }}"
        satellite_username: "{{ sat_user }}"
        satellite_password: "{{ sat_passwd }}"
        satellite_organization: "{{ organization }}"
        # satellite_content_credentials already set up in pre-task
      environment: "{{ default_http_proxy_url is defined | ternary({ 'http_proxy': default_http_proxy_url, 'https_proxy': default_http_proxy_url }), omit) }}"
      tags: gpg-keys
    - role: redhat.satellite.sync_plans
      vars:
        satellite_server_url: "{{ sat_url }}"
        satellite_username: "{{ sat_user }}"
        satellite_password: "{{ sat_passwd }}"
        satellite_organization: "{{ organization }}"
        satellite_sync_plans:
          - name: "{{ sync_plan }}"
            interval: "{{ sync_interval }}"
            sync_date: "2020-01-01 01:04:00 UTC"
            products: "{{ products }}"
      tags: syncplans
    - role: repos
      tags: repos
    - role: environments
      tags: environments
    - role: content-views
      tags: content-views
    - role: host-collections
      tags: host-collections
    - role: ptable
      tags: ptable
    - role: os
      tags: os
    - role: domains
      tags: domains
    - role: subnets
      tags: subnets
  # - role: compute-resources
  #   tags: compute-resources
    - role: host-groups
      tags: host-groups
    - role: activationkeys
      tags: activationkeys

