- hosts: all
  vars_files:
  - vars.yml
  #- vars_generated.yml
  - passwd.yml

  collections:
    - redhat.satellite

  
  roles: 
    - role: redhat.satellite.manifest
      vars:
        satellite_server_url: "{{ sat_url }}"
        satellite_username: "{{ sat_user }}"
        satellite_password: "{{ sat_passwd }}"
        satellite_organization: "{{ organization }}"
        satellite_manifest_path: "~/manifest.zip"
      tags: manifest
    - role: firewalld
      tags: firewalld
    - role: locations
    - role: proxy
    - role: settings
    - role: gpg-keys
      tags: gpg-keys
    - role: syncplans
      tags: syncplans
    - role: repos
      tags: repos
    - role: environments
      tags: environments
    - role: content-views
      tags: content-views
    - role: host-collections
      tags: host-collections
    - role: ptable
      tags: ptable
    - role: os
      tags: os
    - role: domains
      tags: domains
    - role: subnets
      tags: subnets
  # - role: compute-resources
  #   tags: compute-resources
    - role: host-groups
      tags: host-groups
    - role: activationkeys
      tags: activationkeys

  pre_tasks:
    - name: Copy manifest to target Satellite
      copy:
        src: "~/manifest.zip"
        dest: /root/manifest.zip
 
